-- =====================================================================
-- Persona Fit — enriquecimento do catálogo de exercícios
--
-- +251 exercícios: de 271 para 522. Fonte: yuhonas/free-exercise-db
-- (CC0), a mesma que já alimenta as imagens do catálogo — então todos
-- nascem COM as duas imagens de demonstração.
--
-- Critérios de seleção, nesta ordem:
--   1. Nada de nível `expert` (decisão do dev).
--   2. Kettlebell completo (decisão do dev).
--   3. Near-duplicatas descartadas na mão: 63 candidatos caíram por serem
--      variação de pegada/lateralidade do mesmo movimento (seis roscas de
--      punho, quatro flexões inclinadas, três extensões de tríceps
--      curvado...). Quantidade sem variedade real pioraria o prompt da IA,
--      que recebe só 8 exercícios por grupo.
--   4. Nenhum nome colide com o catálogo existente (validado antes de gerar).
--
-- Nomes em PT-BR seguindo a convenção "<Nome> (<equipamento>)" já usada. O
-- termo que não se traduz fica em inglês, com o português quando existe —
-- "Bom dia pernas estendidas (good morning)".
--
-- `requires_lower_limbs` classificado por músculo primário + categoria, com
-- 19 correções manuais para movimentos que usam a perna como apoio ou
-- alavanca sem citá-la no nome (sit-up, superman, prancha caminhando).
--
-- Idempotente: `on conflict ... do nothing` sobre o índice parcial do seed.
-- =====================================================================

do $$
declare
  g_back uuid;
  g_biceps uuid;
  g_cardio uuid;
  g_chest uuid;
  g_core uuid;
  g_full_body uuid;
  g_legs uuid;
  g_shoulders uuid;
  g_triceps uuid;
begin
  select id into g_back from public.exercise_groups where slug = 'back';
  select id into g_biceps from public.exercise_groups where slug = 'biceps';
  select id into g_cardio from public.exercise_groups where slug = 'cardio';
  select id into g_chest from public.exercise_groups where slug = 'chest';
  select id into g_core from public.exercise_groups where slug = 'core';
  select id into g_full_body from public.exercise_groups where slug = 'full_body';
  select id into g_legs from public.exercise_groups where slug = 'legs';
  select id into g_shoulders from public.exercise_groups where slug = 'shoulders';
  select id into g_triceps from public.exercise_groups where slug = 'triceps';

  insert into public.exercises
    (group_id, name, equipment, is_compound, modality, image_urls, requires_lower_limbs)
  values
    (g_back, 'Barra fixa assistida com elástico', 'equipamento', true, 'musculacao', public.exercise_image_urls('Band_Assisted_Pull-Up'), false),
    (g_back, 'Barra fixa com triângulo (V-bar)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('V-Bar_Pullup'), false),
    (g_back, 'Barra fixa escapular', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Scapular_Pull-Up'), false),
    (g_back, 'Bom dia pernas estendidas (good morning)', 'barra', true, 'musculacao', public.exercise_image_urls('Stiff_Leg_Barbell_Good_Morning'), true),
    (g_back, 'Encolhimento atrás do corpo (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Barbell_Shrug_Behind_The_Back'), false),
    (g_back, 'Encolhimento na máquina', 'máquina', false, 'musculacao', public.exercise_image_urls('Leverage_Shrug'), false),
    (g_back, 'Encolhimento no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Shrugs'), false),
    (g_back, 'Pulldown de braços retos (barra)', 'cabo', false, 'musculacao', public.exercise_image_urls('Straight-Arm_Pulldown'), false),
    (g_back, 'Pulldown de braços retos inclinado (cabo)', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Incline_Pushdown'), false),
    (g_back, 'Pulldown de braços retos na corda', 'cabo', false, 'musculacao', public.exercise_image_urls('Rope_Straight-Arm_Pulldown'), false),
    (g_back, 'Puxada supinada (pulley)', 'cabo', true, 'musculacao', public.exercise_image_urls('Underhand_Cable_Pulldowns'), false),
    (g_back, 'Puxada unilateral (pulley)', 'cabo', true, 'musculacao', public.exercise_image_urls('One_Arm_Lat_Pulldown'), false),
    (g_back, 'Remada T-bar com triângulo', 'barra', true, 'musculacao', public.exercise_image_urls('T-Bar_Row_with_Handle'), false),
    (g_back, 'Remada alta (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Standing_Dumbbell_Upright_Row'), false),
    (g_back, 'Remada alta com elástico', 'elástico', true, 'musculacao', public.exercise_image_urls('Upright_Row_-_With_Bands'), false),
    (g_back, 'Remada cavalinho unilateral', 'barra', true, 'musculacao', public.exercise_image_urls('One-Arm_Long_Bar_Row'), false),
    (g_back, 'Remada curvada (Smith)', 'máquina', true, 'musculacao', public.exercise_image_urls('Smith_Machine_Bent_Over_Row'), false),
    (g_back, 'Remada curvada pegada neutra (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Bent_Over_Two-Dumbbell_Row_With_Palms_In'), false),
    (g_back, 'Remada deitado no banco (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Lying_Cambered_Barbell_Row'), false),
    (g_back, 'Remada invertida na fita', 'equipamento', true, 'musculacao', public.exercise_image_urls('Inverted_Row_with_Straps'), false),
    (g_back, 'Remada na máquina articulada', 'máquina', true, 'musculacao', public.exercise_image_urls('Leverage_Iso_Row'), false),
    (g_back, 'Remada na polia alta ajoelhado', 'cabo', true, 'musculacao', public.exercise_image_urls('Kneeling_High_Pulley_Row'), false),
    (g_back, 'Remada no banco inclinado (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Incline_Bench_Pull'), false),
    (g_back, 'Remada no banco inclinado (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Dumbbell_Incline_Row'), false),
    (g_back, 'Remada no trenó', 'equipamento', true, 'musculacao', public.exercise_image_urls('Sled_Row'), false),
    (g_back, 'Remada unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('One-Arm_Kettlebell_Row'), false),
    (g_back, 'Remada unilateral com rotação (cabo)', 'cabo', true, 'musculacao', public.exercise_image_urls('Shotgun_Row'), false),
    (g_back, 'Sumô high pull (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Sumo_High_Pull'), false),
    (g_biceps, 'Clean bottoms-up (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Bottoms-Up_Clean_From_The_Hang_Position'), false),
    (g_biceps, 'Rosca Scott unilateral (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('One_Arm_Dumbbell_Preacher_Curl'), false),
    (g_biceps, 'Rosca concentrada em pé (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('Standing_Concentration_Curl'), false),
    (g_biceps, 'Rosca de dedos (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Finger_Curls'), false),
    (g_biceps, 'Rosca de punho invertida (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Palms-Down_Wrist_Curl_Over_A_Bench'), false),
    (g_biceps, 'Rosca de punho sentado (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Seated_Palm-Up_Barbell_Wrist_Curl'), false),
    (g_biceps, 'Rosca de punho sentado (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Seated_Dumbbell_Palms-Up_Wrist_Curl'), false),
    (g_biceps, 'Rosca deitado no banco inclinado (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Barbell_Curls_Lying_Against_An_Incline'), false),
    (g_biceps, 'Rosca deitado supino (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Lying_Supine_Dumbbell_Curl'), false),
    (g_biceps, 'Rosca inclinada (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Incline_Dumbbell_Curl'), false),
    (g_biceps, 'Rosca interna sentado (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Seated_Dumbbell_Inner_Biceps_Curl'), false),
    (g_biceps, 'Rosca inversa (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Reverse_Barbell_Curl'), false),
    (g_biceps, 'Rosca martelo cruzada (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Cross_Body_Hammer_Curl'), false),
    (g_biceps, 'Rosca martelo inclinada (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Incline_Hammer_Curls'), false),
    (g_biceps, 'Rosca pegada aberta (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Wide-Grip_Standing_Barbell_Curl'), false),
    (g_biceps, 'Rosca pegada fechada (barra W)', 'barra', false, 'musculacao', public.exercise_image_urls('Close-Grip_EZ_Bar_Curl'), false),
    (g_biceps, 'Rotação de punho (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Wrist_Rotations_with_Straight_Bar'), false),
    (g_cardio, 'Patinação', 'equipamento', false, 'musculacao', public.exercise_image_urls('Skating'), true),
    (g_cardio, 'Prowler sprint (trenó)', 'equipamento', true, 'musculacao', public.exercise_image_urls('Prowler_Sprint'), true),
    (g_chest, 'Crossover com elástico', 'elástico', true, 'musculacao', public.exercise_image_urls('Cross_Over_-_With_Bands'), false),
    (g_chest, 'Crossover unilateral (cabo)', 'cabo', false, 'musculacao', public.exercise_image_urls('Single-Arm_Cable_Crossover'), false),
    (g_chest, 'Crucifixo cruzado no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Iron_Cross'), false),
    (g_chest, 'Crucifixo declinado (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Decline_Dumbbell_Flyes'), false),
    (g_chest, 'Crucifixo inclinado com rotação (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Incline_Dumbbell_Flyes_-_With_A_Twist'), false),
    (g_chest, 'Crucifixo reto unilateral (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('One-Arm_Flat_Bench_Dumbbell_Flye'), false),
    (g_chest, 'Elevação frontal com pullover (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Front_Raise_And_Pullover'), false),
    (g_chest, 'Supino declinado (Smith)', 'máquina', true, 'musculacao', public.exercise_image_urls('Decline_Smith_Press'), false),
    (g_chest, 'Supino declinado (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Decline_Dumbbell_Bench_Press'), false),
    (g_chest, 'Supino declinado (máquina)', 'máquina', true, 'musculacao', public.exercise_image_urls('Leverage_Decline_Chest_Press'), false),
    (g_chest, 'Supino inclinado no cabo', 'cabo', true, 'musculacao', public.exercise_image_urls('Incline_Cable_Chest_Press'), false),
    (g_chest, 'Supino inclinado pegada neutra (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Hammer_Grip_Incline_DB_Bench_Press'), false),
    (g_chest, 'Supino no cabo (sentado)', 'cabo', true, 'musculacao', public.exercise_image_urls('Cable_Chest_Press'), false),
    (g_chest, 'Supino no cabo em pé', 'cabo', true, 'musculacao', public.exercise_image_urls('Standing_Cable_Chest_Press'), false),
    (g_chest, 'Supino no solo alternado (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Alternating_Floor_Press'), false),
    (g_chest, 'Supino no solo unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Extended_Range_One-Arm_Kettlebell_Floor_Press'), false),
    (g_chest, 'Supino reto com elástico', 'elástico', true, 'musculacao', public.exercise_image_urls('Bench_Press_-_With_Bands'), false),
    (g_chest, 'Supino reto unilateral (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('One_Arm_Dumbbell_Bench_Press'), false),
    (g_chest, 'Svend press (anilha)', 'equipamento', true, 'musculacao', public.exercise_image_urls('Svend_Press'), false),
    (g_core, 'Abdominal com braços estendidos', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Crunch_-_Hands_Overhead'), false),
    (g_core, 'Abdominal com joelhos flexionados', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Tuck_Crunch'), true),
    (g_core, 'Abdominal com pernas na bola', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Crunch_-_Legs_On_Exercise_Ball'), true),
    (g_core, 'Abdominal cruzado', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Cross-Body_Crunch'), true),
    (g_core, 'Abdominal oblíquo declinado', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Decline_Oblique_Crunch'), false),
    (g_core, 'Abdominal oblíquo no solo', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Oblique_Crunches_-_On_The_Floor'), false),
    (g_core, 'Abdominal reverso declinado', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Decline_Reverse_Crunch'), true),
    (g_core, 'Abdominal sentado no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Seated_Crunch'), false),
    (g_core, 'Bottoms up (elevação de quadril deitado)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Bottoms_Up'), true),
    (g_core, 'Butt-ups (prancha com elevação de quadril)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Butt-Ups'), true),
    (g_core, 'Canivete lateral', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Side_Jackknife'), true),
    (g_core, 'Cocoon (recolhimento de joelhos)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Cocoons'), true),
    (g_core, 'Cotovelo no joelho (abdominal)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Elbow_to_Knee'), true),
    (g_core, 'Elevação de pernas no banco reto', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Flat_Bench_Lying_Leg_Raise'), true),
    (g_core, 'Figura 8 (kettlebell)', 'kettlebell', false, 'musculacao', public.exercise_image_urls('Kettlebell_Figure_8'), true),
    (g_core, 'Flexão lateral de tronco (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Barbell_Side_Bend'), false),
    (g_core, 'Flexão lateral de tronco (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('Dumbbell_Side_Bend'), false),
    (g_core, 'Judo flip no cabo', 'cabo', true, 'musculacao', public.exercise_image_urls('Cable_Judo_Flip'), false),
    (g_core, 'Landmine 180°', 'barra', true, 'musculacao', public.exercise_image_urls('Landmine_180s'), false),
    (g_core, 'Passagem entre as pernas (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Pass_Between_The_Legs'), true),
    (g_core, 'Recolhimento de pernas sentado', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Seated_Leg_Tucks'), true),
    (g_core, 'Rotação de tronco sentado (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Seated_Barbell_Twist'), false),
    (g_core, 'Sit-up parcial (3/4)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('3_4_Sit-Up'), true),
    (g_core, 'Spell caster (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Spell_Caster'), false),
    (g_core, 'Spider crawl (prancha caminhando)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Spider_Crawl'), true),
    (g_core, 'Windmill (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Windmill'), false),
    (g_core, 'Windmill avançado (kettlebell)', 'kettlebell', false, 'musculacao', public.exercise_image_urls('Advanced_Kettlebell_Windmill'), false),
    (g_full_body, 'Agachamento de mobilidade', 'peso corporal', false, 'generico', public.exercise_image_urls('Sit_Squats'), true),
    (g_full_body, 'Alcance dos pés deitado', 'peso corporal', false, 'generico', public.exercise_image_urls('Toe_Touchers'), true),
    (g_full_body, 'Alongamento de isquiotibiais 90/90', 'peso corporal', false, 'generico', public.exercise_image_urls('90_90_Hamstring'), true),
    (g_full_body, 'Alongamento de lombar em flexão', 'peso corporal', false, 'generico', public.exercise_image_urls('Lower_Back_Curl'), true),
    (g_full_body, 'Alongamento de peito com cotovelos atrás', 'peso corporal', false, 'generico', public.exercise_image_urls('Elbows_Back'), false),
    (g_full_body, 'Alongamento de peito na bola suíça', 'bola suíça', false, 'generico', public.exercise_image_urls('Chest_Stretch_on_Stability_Ball'), false),
    (g_full_body, 'Alongamento em abertura (straddle)', 'peso corporal', false, 'generico', public.exercise_image_urls('The_Straddle'), true),
    (g_full_body, 'Anfersen (calcanhar no glúteo)', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Double_Leg_Butt_Kick'), true),
    (g_full_body, 'Arrasto de trenó com cinto', 'equipamento', true, 'crossfit', public.exercise_image_urls('Sled_Drag_-_Harness'), true),
    (g_full_body, 'Arrasto de trenó para trás', 'equipamento', true, 'crossfit', public.exercise_image_urls('Backward_Drag'), true),
    (g_full_body, 'Arrasto frontal com press', 'equipamento', true, 'crossfit', public.exercise_image_urls('Forward_Drag_with_Press'), true),
    (g_full_body, 'Arremesso de baixo (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Medicine_Ball_Scoop_Throw'), true),
    (g_full_body, 'Arremesso de peito deitado (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Supine_Chest_Throw'), true),
    (g_full_body, 'Arremesso para trás (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Backward_Medicine_Ball_Throw'), true),
    (g_full_body, 'Atlas stone (simulador)', 'equipamento', true, 'crossfit', public.exercise_image_urls('Atlas_Stone_Trainer'), true),
    (g_full_body, 'Bear crawl com arrasto de trenó', 'equipamento', true, 'crossfit', public.exercise_image_urls('Bear_Crawl_Sled_Drags'), true),
    (g_full_body, 'Box jump em série', 'equipamento', true, 'crossfit', public.exercise_image_urls('Box_Jump_Multiple_Response'), true),
    (g_full_body, 'Box jump lateral', 'equipamento', true, 'crossfit', public.exercise_image_urls('Lateral_Box_Jump'), true),
    (g_full_body, 'Box skip', 'equipamento', true, 'crossfit', public.exercise_image_urls('Box_Skip'), true),
    (g_full_body, 'Carioca (deslocamento cruzado)', 'peso corporal', false, 'crossfit', public.exercise_image_urls('Carioca_Quick_Step'), true),
    (g_full_body, 'Clean (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Clean'), true),
    (g_full_body, 'Clean deadlift (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Clean_Deadlift'), true),
    (g_full_body, 'Clean dos blocos (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Clean_from_Blocks'), true),
    (g_full_body, 'Clean pull (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Clean_Pull'), true),
    (g_full_body, 'Clean shrug (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Clean_Shrug'), true),
    (g_full_body, 'Crucifix (sustentação com halteres)', 'equipamento', false, 'crossfit', public.exercise_image_urls('Crucifix'), true),
    (g_full_body, 'Círculos de braço', 'peso corporal', false, 'generico', public.exercise_image_urls('Arm_Circles'), false),
    (g_full_body, 'Círculos de joelho', 'peso corporal', true, 'generico', public.exercise_image_urls('Knee_Circles'), true),
    (g_full_body, 'Círculos de punho', 'peso corporal', false, 'generico', public.exercise_image_urls('Wrist_Circles'), false),
    (g_full_body, 'Círculos de quadril em pé', 'peso corporal', false, 'generico', public.exercise_image_urls('Standing_Hip_Circles'), true),
    (g_full_body, 'Círculos de tornozelo', 'peso corporal', false, 'generico', public.exercise_image_urls('Ankle_Circles'), true),
    (g_full_body, 'Depth jump', 'equipamento', true, 'crossfit', public.exercise_image_urls('Depth_Jump_Leap'), true),
    (g_full_body, 'Deslocamento lateral no step', 'equipamento', true, 'crossfit', public.exercise_image_urls('Side_to_Side_Box_Shuffle'), true),
    (g_full_body, 'Elevação de perna para trás (mobilidade)', 'peso corporal', false, 'generico', public.exercise_image_urls('Rear_Leg_Raises'), true),
    (g_full_body, 'Elevação frontal de perna (mobilidade)', 'peso corporal', false, 'generico', public.exercise_image_urls('Front_Leg_Raises'), true),
    (g_full_body, 'Elevação lateral de perna (mobilidade)', 'peso corporal', false, 'generico', public.exercise_image_urls('Side_Leg_Raises'), true),
    (g_full_body, 'Foam roll de isquiotibiais', 'rolo', false, 'generico', public.exercise_image_urls('Hamstring-SMR'), true),
    (g_full_body, 'Foam roll de latíssimo', 'rolo', false, 'generico', public.exercise_image_urls('Latissimus_Dorsi-SMR'), false),
    (g_full_body, 'Golpes de marreta', 'equipamento', true, 'crossfit', public.exercise_image_urls('Sledgehammer_Swings'), true),
    (g_full_body, 'Hang clean (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Hang_Clean'), true),
    (g_full_body, 'Hang clean abaixo dos joelhos (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Hang_Clean_-_Below_the_Knees'), true),
    (g_full_body, 'Jerk balance (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Jerk_Balance'), true),
    (g_full_body, 'Levantamento terra com axle', 'equipamento', true, 'crossfit', public.exercise_image_urls('Axle_Deadlift'), true),
    (g_full_body, 'Log lift (tronco)', 'equipamento', true, 'crossfit', public.exercise_image_urls('Log_Lift'), true),
    (g_full_body, 'Muscle snatch (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Muscle_Snatch'), true),
    (g_full_body, 'Passe de peito (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Medicine_Ball_Chest_Pass'), true),
    (g_full_body, 'Power clean dos blocos (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Power_Clean_from_Blocks'), true),
    (g_full_body, 'Power snatch dos blocos (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Power_Snatch_from_Blocks'), true),
    (g_full_body, 'Push press atrás da nuca (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Push_Press_-_Behind_the_Neck'), true),
    (g_full_body, 'Rickshaw carry', 'equipamento', true, 'crossfit', public.exercise_image_urls('Rickshaw_Carry'), true),
    (g_full_body, 'Rotação completa (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Medicine_Ball_Full_Twist'), true),
    (g_full_body, 'Rotação de tronco na bola', 'bola suíça', false, 'generico', public.exercise_image_urls('Torso_Rotation'), false),
    (g_full_body, 'Salto afundado', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Split_Jump'), true),
    (g_full_body, 'Salto com joelhos ao peito', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Knee_Tuck_Jump'), true),
    (g_full_body, 'Salto estrela', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Star_Jump'), true),
    (g_full_body, 'Salto horizontal parado', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Standing_Long_Jump'), true),
    (g_full_body, 'Salto lateral', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Lateral_Bound'), true),
    (g_full_body, 'Salto no banco', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Bench_Jump'), true),
    (g_full_body, 'Salto rocket', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Rocket_Jump'), true),
    (g_full_body, 'Salto tesoura', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Scissors_Jump'), true),
    (g_full_body, 'Saltos laterais no cone', 'equipamento', true, 'crossfit', public.exercise_image_urls('Lateral_Cone_Hops'), true),
    (g_full_body, 'Saltos sobre barreiras', 'equipamento', true, 'crossfit', public.exercise_image_urls('Hurdle_Hops'), true),
    (g_full_body, 'Sandbag load (carregar saco)', 'equipamento', true, 'crossfit', public.exercise_image_urls('Sandbag_Load'), true),
    (g_full_body, 'Skipping rápido', 'peso corporal', true, 'crossfit', public.exercise_image_urls('Fast_Skipping'), true),
    (g_full_body, 'Slam acima da cabeça (medicine ball)', 'medicine ball', true, 'crossfit', public.exercise_image_urls('Overhead_Slam'), true),
    (g_full_body, 'Snatch balance (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Snatch_Balance'), true),
    (g_full_body, 'Snatch deadlift (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Snatch_Deadlift'), true),
    (g_full_body, 'Snatch shrug (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Snatch_Shrug'), true),
    (g_full_body, 'Split clean (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Split_Clean'), true),
    (g_full_body, 'Split jerk (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Split_Jerk'), true),
    (g_full_body, 'Stiff pernas afastadas (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Wide_Stance_Stiff_Legs'), true),
    (g_full_body, 'Superman (extensão de lombar)', 'peso corporal', true, 'generico', public.exercise_image_urls('Superman'), true),
    (g_full_body, 'Suspensão unilateral na barra', 'equipamento', false, 'generico', public.exercise_image_urls('One_Handed_Hang'), false),
    (g_full_body, 'Swing vertical (halter)', 'halteres', true, 'crossfit', public.exercise_image_urls('Vertical_Swing'), true),
    (g_full_body, 'Terra romeno com déficit (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Romanian_Deadlift_from_Deficit'), true),
    (g_full_body, 'Tire flip (virar pneu)', 'equipamento', true, 'crossfit', public.exercise_image_urls('Tire_Flip'), true),
    (g_full_body, 'Vacuum abdominal', 'peso corporal', false, 'generico', public.exercise_image_urls('Stomach_Vacuum'), false),
    (g_full_body, 'Yoke walk (caminhada com yoke)', 'equipamento', true, 'crossfit', public.exercise_image_urls('Yoke_Walk'), true),
    (g_legs, 'Adução de quadril com elástico', 'elástico', false, 'musculacao', public.exercise_image_urls('Band_Hip_Adductions'), true),
    (g_legs, 'Adução de quadril no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Hip_Adduction'), true),
    (g_legs, 'Afundo caminhando (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Barbell_Walking_Lunge'), true),
    (g_legs, 'Afundo com passagem do peso (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Lunge_Pass_Through'), true),
    (g_legs, 'Agachamento (Smith)', 'máquina', true, 'musculacao', public.exercise_image_urls('Smith_Machine_Squat'), true),
    (g_legs, 'Agachamento (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Dumbbell_Squat'), true),
    (g_legs, 'Agachamento Frankenstein (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Frankenstein_Squat'), true),
    (g_legs, 'Agachamento afundado (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Split_Squat_with_Dumbbells'), true),
    (g_legs, 'Agachamento búlgaro (Smith)', 'máquina', true, 'musculacao', public.exercise_image_urls('Smith_Single-Leg_Split_Squat'), true),
    (g_legs, 'Agachamento com elástico', 'elástico', true, 'musculacao', public.exercise_image_urls('Squats_-_With_Bands'), true),
    (g_legs, 'Agachamento frontal (dois kettlebells)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Front_Squats_With_Two_Kettlebells'), true),
    (g_legs, 'Agachamento lateral (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Barbell_Side_Split_Squat'), true),
    (g_legs, 'Agachamento na cadeira', 'máquina', true, 'musculacao', public.exercise_image_urls('Chair_Squat'), true),
    (g_legs, 'Agachamento olímpico (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Olympic_Squat'), true),
    (g_legs, 'Agachamento sumô (halter)', 'halteres', true, 'musculacao', public.exercise_image_urls('Plie_Dumbbell_Squat'), true),
    (g_legs, 'Cadeira extensora unilateral', 'máquina', false, 'musculacao', public.exercise_image_urls('Single-Leg_Leg_Extension'), true),
    (g_legs, 'Clean unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('One-Arm_Kettlebell_Clean'), true),
    (g_legs, 'Coice de glúteo (peso corporal)', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Glute_Kickback'), true),
    (g_legs, 'Dead clean (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Dead_Clean'), true),
    (g_legs, 'Elevação de quadril (ponte)', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Butt_Lift_Bridge'), true),
    (g_legs, 'Elevação de quadril unilateral', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Single_Leg_Glute_Bridge'), true),
    (g_legs, 'Flexora em pé (máquina)', 'máquina', false, 'musculacao', public.exercise_image_urls('Standing_Leg_Curl'), true),
    (g_legs, 'Flexora na bola suíça', 'bola suíça', false, 'musculacao', public.exercise_image_urls('Ball_Leg_Curl'), true),
    (g_legs, 'Flexão de quadril com elástico', 'elástico', true, 'musculacao', public.exercise_image_urls('Hip_Flexion_with_Band'), true),
    (g_legs, 'Hang clean (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Hang_Clean'), true),
    (g_legs, 'Jerk dip (barra)', 'barra', true, 'crossfit', public.exercise_image_urls('Jerk_Dip_Squat'), true),
    (g_legs, 'Levantamento terra na máquina', 'máquina', true, 'musculacao', public.exercise_image_urls('Leverage_Deadlift'), true),
    (g_legs, 'Levantamento terra no cabo', 'cabo', true, 'musculacao', public.exercise_image_urls('Cable_Deadlifts'), true),
    (g_legs, 'Levantamento terra unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_One-Legged_Deadlift'), true),
    (g_legs, 'Monster walk (caminhada com elástico)', 'elástico', true, 'musculacao', public.exercise_image_urls('Monster_Walk'), true),
    (g_legs, 'Panturrilha em pé (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Standing_Barbell_Calf_Raise'), true),
    (g_legs, 'Panturrilha inversa (Smith)', 'máquina', false, 'musculacao', public.exercise_image_urls('Smith_Machine_Reverse_Calf_Raises'), true),
    (g_legs, 'Panturrilha na máquina de press', 'máquina', false, 'musculacao', public.exercise_image_urls('Calf_Press'), true),
    (g_legs, 'Panturrilha sentado (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Barbell_Seated_Calf_Raise'), true),
    (g_legs, 'Pull through (cabo)', 'cabo', true, 'musculacao', public.exercise_image_urls('Pull_Through'), true),
    (g_legs, 'Step-up com elevação de joelho', 'peso corporal', true, 'musculacao', public.exercise_image_urls('Step-up_with_Knee_Raise'), true),
    (g_legs, 'Stiff (Smith)', 'máquina', true, 'musculacao', public.exercise_image_urls('Smith_Machine_Stiff-Legged_Deadlift'), true),
    (g_shoulders, 'Anti-gravity press (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Anti-Gravity_Press'), false),
    (g_shoulders, 'Arnold press (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Arnold_Press'), false),
    (g_shoulders, 'Bradford press em pé (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Standing_Bradford_Press'), false),
    (g_shoulders, 'Car drivers (rotação com anilha)', 'barra', false, 'musculacao', public.exercise_image_urls('Car_Drivers'), false),
    (g_shoulders, 'Clean and jerk unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('One-Arm_Kettlebell_Clean_and_Jerk'), false),
    (g_shoulders, 'Crucifixo inverso (máquina)', 'máquina', false, 'musculacao', public.exercise_image_urls('Reverse_Machine_Flyes'), false),
    (g_shoulders, 'Crucifixo inverso no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Rear_Delt_Fly'), false),
    (g_shoulders, 'Desenvolvimento alternado (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Seesaw_Press'), false),
    (g_shoulders, 'Desenvolvimento em pé (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Standing_Dumbbell_Press'), false),
    (g_shoulders, 'Desenvolvimento militar (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Two-Arm_Kettlebell_Military_Press'), false),
    (g_shoulders, 'Desenvolvimento militar em pé (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Standing_Military_Press'), false),
    (g_shoulders, 'Desenvolvimento no cabo', 'cabo', true, 'musculacao', public.exercise_image_urls('Cable_Shoulder_Press'), false),
    (g_shoulders, 'Desenvolvimento sentado (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Seated_Dumbbell_Press'), false),
    (g_shoulders, 'Desenvolvimento sentado (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Seated_Press'), false),
    (g_shoulders, 'Elevação alternada de deltoides (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Alternating_Deltoid_Raise'), false),
    (g_shoulders, 'Elevação de ombros no banco inclinado (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Dumbbell_Incline_Shoulder_Raise'), false),
    (g_shoulders, 'Elevação frontal inclinada (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Front_Incline_Dumbbell_Raise'), false),
    (g_shoulders, 'Elevação lateral com frontal (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Side_Laterals_to_Front_Raise'), false),
    (g_shoulders, 'Elevação lateral inclinada unilateral (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('One-Arm_Incline_Lateral_Raise'), false),
    (g_shoulders, 'Elevação lateral unilateral (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('One-Arm_Side_Laterals'), false),
    (g_shoulders, 'Elevação posterior apoiado no banco (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench'), false),
    (g_shoulders, 'Jerk unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('One-Arm_Kettlebell_Jerk'), false),
    (g_shoulders, 'Push press unilateral (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('One-Arm_Kettlebell_Push_Press'), false),
    (g_shoulders, 'Remada na polia baixa até o queixo', 'cabo', true, 'musculacao', public.exercise_image_urls('Low_Pulley_Row_To_Neck'), false),
    (g_shoulders, 'Remada para deltoide posterior (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Barbell_Rear_Delt_Row'), false),
    (g_shoulders, 'Rotação externa (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('External_Rotation'), false),
    (g_shoulders, 'Scaption (elevação no plano da escápula)', 'halteres', false, 'musculacao', public.exercise_image_urls('Dumbbell_Scaption'), false),
    (g_shoulders, 'Turkish get-up estilo afundo (kettlebell)', 'kettlebell', true, 'musculacao', public.exercise_image_urls('Kettlebell_Turkish_Get-Up_Lunge_style'), false),
    (g_triceps, 'JM press (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('JM_Press'), false),
    (g_triceps, 'Mergulho na máquina (dip machine)', 'máquina', true, 'musculacao', public.exercise_image_urls('Dip_Machine'), false),
    (g_triceps, 'Supino pegada fechada (barra)', 'barra', true, 'musculacao', public.exercise_image_urls('Close-Grip_Barbell_Bench_Press'), false),
    (g_triceps, 'Supino pegada fechada (halteres)', 'halteres', true, 'musculacao', public.exercise_image_urls('Close-Grip_Dumbbell_Press'), false),
    (g_triceps, 'Tríceps coice sentado (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension'), false),
    (g_triceps, 'Tríceps com toalha', 'peso corporal', false, 'musculacao', public.exercise_image_urls('Standing_Towel_Triceps_Extension'), false),
    (g_triceps, 'Tríceps francês em pé (barra)', 'barra', false, 'musculacao', public.exercise_image_urls('Standing_Overhead_Barbell_Triceps_Extension'), false),
    (g_triceps, 'Tríceps francês em pé (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Standing_Dumbbell_Triceps_Extension'), false),
    (g_triceps, 'Tríceps na máquina', 'máquina', false, 'musculacao', public.exercise_image_urls('Machine_Triceps_Extension'), false),
    (g_triceps, 'Tríceps na polia baixa', 'cabo', false, 'musculacao', public.exercise_image_urls('Low_Cable_Triceps_Extension'), false),
    (g_triceps, 'Tríceps pulley pegada inversa', 'cabo', false, 'musculacao', public.exercise_image_urls('Reverse_Grip_Triceps_Pushdown'), false),
    (g_triceps, 'Tríceps testa declinado (barra W)', 'barra', false, 'musculacao', public.exercise_image_urls('Decline_EZ_Bar_Triceps_Extension'), false),
    (g_triceps, 'Tríceps testa declinado (halteres)', 'halteres', false, 'musculacao', public.exercise_image_urls('Decline_Dumbbell_Triceps_Extension'), false),
    (g_triceps, 'Tríceps testa no cabo', 'cabo', false, 'musculacao', public.exercise_image_urls('Cable_Lying_Triceps_Extension'), false),
    (g_triceps, 'Tríceps unilateral pegada pronada (halter)', 'halteres', false, 'musculacao', public.exercise_image_urls('One_Arm_Pronated_Dumbbell_Triceps_Extension'), false)
  on conflict (group_id, name) where owner_id is null do nothing;
end $$;
